export default {
  UPDATE_HEADER_TITLE: 'UPDATE_HEADER_TITLE', // 修改头部标题
  UPDATE_HEADER_SHOW_BACK: 'UPDATE_HEADER_SHOW_BACK', // 修改头部返回按钮展示状态
  UPDATE_HEADER_LEFT_HANDLER: 'UPDATE_HEADER_LEFT_HANDLER' // 修改头部返回按钮回调函数
}
